---
deployment:
  tasks:
    - export PATH="/opt/cpanel/ea-nodejs22/bin:$PATH"
    - cd /home/autopecascarreta/repositories/Catlogodepeas
    - npm install --production=false
    - npm run build
    - rm -rf /home/autopecascarreta/public_html/assets
    - cp -r dist/* /home/autopecascarreta/public_html/
